### ISSUE TITLE
Fix call to navigator.mediaDevices.getUserMedia() not work

### ISSUE THREAD

**Issue by niti2539** [niklabh/mattermost-plugin-webrtc-video#21]
I use the new release (0.3.0) but i still get 
"Uncaught TypeError: Cannot read property 'getUserMedia' of undefined." error
I install it on Mattermost EC2.  and I use the webrtc version 0.2.0 in local it works with out any error.
So I change the version on EC2 to 0.2.0 but it still get the same error.
I see the code it should not cause  this error so i don't know how to make it work 
Helpppppp!!!

my config
![webrtc-config](https://user-images.githubusercontent.com/15918153/79050492-965d1080-7c54-11ea-9c92-1f581e714dc8.PNG)
error screen shot
![werrtc-err-screen](https://user-images.githubusercontent.com/15918153/79050497-a2e16900-7c54-11ea-8bd6-5eade5497ecd.PNG)
error code 
![webrtc-error](https://user-images.githubusercontent.com/15918153/79050514-ba205680-7c54-11ea-9ee3-3894c722eefb.PNG)

**Comment by niklabh** [comment]
which browser you are using

**Comment by niti2539** [comment]
> which browser you are using

I try chrome , firefox and microsoft edge beta .
 what you use to test So I can try it.

**Comment by niti2539** [comment]
I think it about http and https on the server(my server use http) i install it . Because i can use it in the localhost.

**Comment by niti2539** [comment]
Yeah , Confirm it's about Http and Https  change to Https solve this .
