### ISSUE TITLE
[feature request] WebRTC Screen sharing

### ISSUE THREAD

**Issue by melroy89** [niklabh/mattermost-plugin-webrtc-video#25]
Hi,

After the features to close the call again, one of the missing features would definitely be screen sharing by using this plugin. Other alternatives like BigBlueButton or Jitsi for example has the ability to share the screen to others.

I know it would be technically possible, eg by using a browser plugin if required (ideally **no** plugin requirement).

References:
* https://github.com/muaz-khan/WebRTC-Experiment/tree/master/screen-sharing
* https://github.com/muaz-khan/WebRTC-Experiment/tree/master/Pluginfree-Screen-Sharing
* https://flashphoner.com/how-to-test-screen-sharing-in-a-webrtc-browser/

![image](https://user-images.githubusercontent.com/628926/80629174-c0834080-8a52-11ea-9333-143c52da4f14.png)

Thanks in advance!

Regards,
Melroy van den Berg

**Comment by aadrian** [comment]
@danger89 see #6

**Comment by melroy89** [comment]
Sorry, duplicate. I will close it for easily keeping track of open issues.
