### ISSUE TITLE
Dist folder missing (no Mattermost tar.gz v1.0.1 version released!)

### ISSUE THREAD

**Issue by melroy89** [niklabh/mattermost-plugin-webrtc-video#26]
Hi,

When I try to upload the new version (using tar.gz, zip definitely won't work) in the admin console, yes I enabled uploading of plugins.

I do get an error message:

> Unable to generate plugin webapp bundle.

![image](https://user-images.githubusercontent.com/628926/80644829-9473b980-8a6a-11ea-875a-94ec838fe9fd.png)

Other plugins do work, but not your webrtc plugin.

I'm using Mattermost Version: 5.21.0 (shipped with GitLab).

Despite the error message. I do see the "WebRTC Video" menu-item in the menu:

![image](https://user-images.githubusercontent.com/628926/80645225-1b289680-8a6b-11ea-973c-64022ab2aef5.png)

Mattermost log file gives:

```
{"level":"error","ts":1588192715.4799285,"caller":"mlog/log.go:175","msg":"Unable to generate plugin webapp bundle.","path":"/api/v4/plugins","request_id":"crojkygactbwbjhwmnhcpw7wzr","ip_addr":"192.168.2.166","user_id":"4qff45rsefgiixufe1juf4riyh","method":"POST","err_where":"installExtractedPlugin","http_code":500,"err_details":"unable to copy webapp bundle directory: mattermost-webrtc-video: stat /var/opt/gitlab/mattermost/plugins/mattermost-webrtc-video/webapp/dist: no such file or directory"}
```

`dist` folder indeed is missing! And not created during install.

![image](https://user-images.githubusercontent.com/628926/80645821-f4b72b00-8a6b-11ea-9ea6-755a95b3cfa1.png)

Regards,
Melroy van den Berg

**Comment by danger89** [comment]
Is `go` required to be installed for this plugin or is the release not correctly made?

**Comment by melroy89** [comment]
Root cause: You didn't create a Mattermost version (only source code) in your latest release: https://github.com/niklabh/mattermost-plugin-webrtc-video/releases/tag/1.0.1

**Comment by araven** [comment]
Could you please release a ready to use plugin for mattermost for the release 1.0.1 to test ? The 1.0.0 appears not to function properly, as far I am testing

**Comment by niklabh** [comment]
https://github.com/niklabh/mattermost-plugin-webrtc-video/releases/tag/1.0.2

**Comment by melroy89** [comment]
Thanks for releasing a new version as well!
