### ISSUE TITLE
Please detail build steps.

### ISSUE THREAD

**Issue by vincnetas** [niklabh/mattermost-plugin-webrtc-video#3]
Really like idea of vendor free video call from mattermost, but pity that plugin is not working, tried to checkout and build it my self to see whats up, but 

`make clean all`

is failing. Could you detail, how to build this project. I'm getting this error :

```
vincentas$ make clean all
go: github.com/mattermost/mattermost-server@v5.12.0+incompatible requires
	willnorris.com/go/imageproxy@v0.8.1-0.20190326225038-d4246a08fdec: invalid pseudo-version: does not match version-control timestamp (2019-04-22T23:49:45Z)
make: build/bin/manifest: Command not found
build/setup.mk:13: *** "Cannot parse id from plugin.json".  Stop.
```

**Comment by franckadil** [comment]
Hi @vincnetas, can you please try using go version go1.13 linux/amd64 and run make clean before your build?

Seems like @niklabh is using an older version of Go, downgrading is the only option until somebody figures out how to improve this build.

Cheers,

Edit: You also want to make sure to locate the project outside of $GOPATH, or allow the use of Go modules within your $GOPATH with an export GO111MODULE=on.

**I tested by running** `export GO111MODULE=on` before `make` .

[Source](https://github.com/mattermost/mattermost-plugin-starter-template)

**Comment by niklabh** [comment]
build step is simple 

```
make
```

command

Please check now i think its working

**Comment by niklabh** [comment]
> Edit: You also want to make sure to locate the project outside of $GOPATH, or allow the use of Go modules within your $GOPATH with an export GO111MODULE=on.
> 
> **I tested by running** `export GO111MODULE=on` before `make` .

can you please do a PR with go1.13

**Comment by niklabh** [comment]
> `make clean all`

This is fixed now.

make command is working. my go verison. go version
go version go1.14 linux/amd64
